:sectnums:
:sectnumlevels: 2
:toc: left
:toclevels: 2
:icons: font
:experimental:

= Micronaut and GraalVM in Practice

== Introduction

Micronaut is a modern, JVM-based full-stack framework for building modular, easily testable microservice and serverless applications. Developed by the creators of the Grails framework and with the support of many Spring developers, who have used their experience in these areas to develop a framework specifically focused on microservices.

Oracle’s newly developed GraalVM will change our view of microservices and cloud capabilities in the Java ecosystem and enable us to compete with native compilations. When Micronaut and GraalVM come together, both architectures can take full advantage of each other, resulting in amazingly efficient applications.

This workshop is an introduction to development with Micronaut on the GraalVM to give you everything you need to get started right away. The following topics will be covered in the workshop:

- Project creation with Micronaut-CLI
- Non-blocking, reactive HTTP Clients and Servers
- Scheduled Task Execution
- Configuration using files and environment variables
- Unit-Tests with and without a server
- Dependency Injection (at compile time)
- Robust interfaces (Retries, Circuit Breakers, Fallback)
- GraalVM Native Image
- Build using Docker without local GraalVM installation

In order to participate in the workshop, you need:

- a notebook (don't forget the power supply)
- a development environment (where you know your way around)
- an installed GraalVM
- the native image tool

All participants receive detailed information in advance about the preparation.

== Let's go

1. Lesson: link:list[A little exercise about the *GraalVM Native Image* tool.]
2. Lesson: link:beers[A hands-on workshop as an introduction to *Micronaut*.]

== Tips

TIP: If you want cURL to add a newline at the end of the output, add `-w "\n"` to your `~/.curlrc` file.

== Copyright

Copyright © Marcus Fihlon
